---
title: "Age trends"
author: "Anthony Staines"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: 
    fig_caption: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

#Purpose
To prepare graphs of coronavirus incidence by age.

```{r setup, include=FALSE}
rm(list=ls())
library(readxl)
library(csodata)
library(RcppRoll)
library(lubridate)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

# Load the data
Latest HSE/HPSC data

```{r}
Irish_Profile <- readRDS('data/Irish_Profile.rds')

  start_date = min(Irish_Profile$Date)
  end_date = max(Irish_Profile$Date) + days(5)
 

excel_sheets('data/Ages.xlsx')
Age_codes <- read_excel('data/Ages.xlsx', sheet = 'Age codes')
```

CSO 2020 population estimates PEA11

```{r}

Pop <- cso_get_data('PEA11') %>%
  filter(Single.Year.of.Age != 'All ages') %>%
  filter(Sex == 'Both sexes') %>%
  select(Single.Year.of.Age,Sex,'2019','2020') %>%
  mutate(Population = (`2019` + `2020`)/2) %>%
  select(Single.Year.of.Age,Sex,Population) %>%
  inner_join(Age_codes,by=c('Single.Year.of.Age' = 'PEA11')) %>%
  group_by(Mean.Age.10,COVID.codes) %>%
  summarise(Population = sum(Population)) %>%
  ungroup() %>%
  arrange(Mean.Age.10)

Pop
sum(Pop$Population) # Check 4,949,470    
    
```

Data are cumulative, need to be made event based

```{r}

#Aged1to4, Aged5to14, Aged15to24, Aged25to34, Aged35to44,Aged45to54, Aged55to64, Aged65up,
Irish_Profile <- Irish_Profile %>%
    mutate(Un_known = c(NA, diff(Unknown))) %>%
  mutate(Un_known.D7 = roll_mean(Un_known, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.0_4 = c(NA, diff(Aged1to4))) %>%
  mutate(Age.D7.0_4 = roll_mean(Age.0_4, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.5_14 = c(NA, diff(Aged5to14))) %>%
  mutate(Age.D7.5_14 = roll_mean(Age.5_14, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.15_24 = c(NA, diff(Aged15to24))) %>%
  mutate(Age.D7.15_24 = roll_mean(Age.15_24, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.25_34 = c(NA, diff(Aged25to34))) %>%
  mutate(Age.D7.25_34 = roll_mean(Age.25_34, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.35_44 = c(NA, diff(Aged35to44))) %>%
  mutate(Age.D7.35_44 = roll_mean(Age.35_44, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.45_54 = c(NA, diff(Aged45to54))) %>%
  mutate(Age.D7.45_54 = roll_mean(Age.45_54, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.55_64 = c(NA, diff(Aged55to64))) %>%
  mutate(Age.D7.55_64 = roll_mean(Age.55_64, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
#  mutate(Age.65plus = c(NA, diff(Aged65up))) %>%
#  mutate(Age.D7.65plus = roll_mean(Age.65plus, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.65_74 = c(NA, diff(Aged65to74))) %>%
  mutate(Age.D7.65_74 = roll_mean(Age.65_74, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.75_84 = c(NA, diff(Aged75to84))) %>%
  mutate(Age.D7.75_84 = roll_mean(Age.75_84, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE)) %>%
  mutate(Age.85plus = c(NA, diff(Aged85up))) %>%
  mutate(Age.D7.85plus = roll_mean(Age.85plus, n=7, align='right', fill=0, normalize=TRUE, na.rm=TRUE))
  
names(Irish_Profile)
```

# Gender

```{r}
Gender <- Irish_Profile %>%
  dplyr:::select(Date,FID,Male,Female,CovidCasesConfirmed) 

  Gender <- Gender %>%
    select(Date,Male,Female) %>%
    mutate(Male   = c(NA,diff(Male))) %>% # Diff lops off the first value 
    mutate(Female = c(NA,diff(Female))) %>%
    filter(!is.na(Female)) %>%
    filter(Date != as_date('2020-04-21')) %>%
    filter(Date != as_date('2020-04-22')) %>%
    pivot_longer(-Date, names_to='Sex', values_to='Cases')

```

```{r}
ggGender <- ggplot(Gender,aes(x=date(Date), y=Cases, group=Sex, colour=Sex)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3) +
  scale_x_date(limits=c(start_date+ days(21),
                        end_date + days(7)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10() +
  xlab('Date') + ylab('Cases (log scale)') +
  ggtitle('Confirmed COVID19 cases over time') +
  theme_light()

ggGender

ggsave('images/COVID19Gender.png', ggGender,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

# Age group

```{r}
Age <- Irish_Profile %>%
  select(Date,FID, Age.0_4:Age.D7.85plus)  %>%
    pivot_longer(-c(Date,FID),
                 names_to=c('AgeType','AgeGroup'),
                 names_pattern = '(Age\\.D7\\.|Age\\.)(.*)',
                 values_to = 'Cases') %>%
  filter(!is.na(Cases)) %>%
  filter(!is.nan(Cases)) %>%
  mutate(Cases = pmax(Cases,0))

#Recode Age
Age <- Age %>%
  inner_join(Age_codes %>% select(COVID.codes,Mean.Age.10), by = c("AgeGroup"="COVID.codes")) %>%
  mutate(AgeGroup = as_factor(AgeGroup)) %>%
  mutate(AgeGroup = fct_reorder(AgeGroup, Mean.Age.10)) %>% # Desired order
  mutate(Cases = pmax(Cases,0))

str(Age)
```

## Recent cases

```{r}
ggAgeMapRecent <- ggplot(Age,
       aes(x=date(Date), y=AgeGroup,
           colour=Cases, fill=Cases)) +
  geom_tile() +
  scale_fill_distiller(palette='OrRd', direction=1,
                       na.value='white') +
  scale_colour_distiller(palette='OrRd', direction=1,
                         na.value='white') +
  scale_x_date(limits=c(start_date + days(180),
                        end_date + days(2)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Age group') +
  ggtitle('Confirmed COVID19 cases by age',subtitle='Recent cases only, Daily and 7 day average') +
  theme_light() +
  facet_wrap(~AgeType)

ggAgeMapRecent

ggsave('images/COVID19AgeMapRecent.png', ggAgeMapRecent,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

## All cases

```{r}
ggAgeMap <- ggplot(Age,
       aes(x=date(Date), y=AgeGroup,
           colour=Cases, fill=Cases)) +
  geom_tile() +
  scale_fill_distiller(palette='OrRd', direction=1,
                       na.value='white') +
  scale_colour_distiller(palette='OrRd', direction=1,
                         na.value='white') +
  scale_x_date(limits=c(start_date + days(21),
                        end_date + days(7)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Age group') +
  ggtitle('Confirmed COVID19 cases by age',subtitle='All cases, Daily and 7 day average') +
  theme_light() +
  facet_wrap(~AgeType)

ggAgeMap

ggsave('images/COVID19AgeMap.png', ggAgeMap,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

# Plot by age and time

## Cases - 7 day average, all time

```{r}
ggAgeLine <- ggplot(Age %>% filter(AgeType == 'Age.D7.'),
       aes(x=date(Date), y=Cases, group = AgeGroup,
           colour=AgeGroup, fill=AgeGroup)) +
  geom_line() +
#  geom_smooth(span=0.1) +
  scale_y_log10(limits=c(1,1350)) +
#  scale_colour_brewer(palette='Dark2', direction=1,
#                         na.value='white') +
#  scale_colour_distiller(palette='OrRd', direction=1,
#                         na.value='white') +
  scale_x_date(limits=c(start_date + days(21),
                        end_date + days(7)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Cases') +
  ggtitle('Confirmed COVID19 cases by age',subtitle='All cases, 7 day average') +
  theme_light()


ggAgeLine

ggsave('images/COVID19AgeLine.png', ggAgeLine,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)

```

## Cases, daily cases, last two months

```{r}
ggAgeLineRecent <- ggplot(Age %>% filter(AgeType == 'Age.'),
       aes(x=date(Date), y=Cases, group = AgeGroup,
           colour=AgeGroup, fill=AgeGroup)) +
#  geom_line() +
  geom_point(alpha=0.05) +
  geom_smooth(span=0.1) +
  scale_y_log10(limits=c(3,1350)) +
#  scale_fill_distiller(palette='OrRd', direction=1,
#                       na.value='white') +
#  scale_colour_brewer(palette='Dark2', direction=1,
#                         na.value='white') +
#  scale_colour_viridis_d(begin='red',end='nlue', direction=1,
 #                        na.value='white') +
  scale_x_date(limits=c(end_date - days(60),
                        end_date + days(7)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Cases') +
  ggtitle('Confirmed COVID19 cases by age',subtitle='All cases, daily numbers') +
  theme_light()

ggAgeLineRecent

ggsave('images/COVID19AgeRecentLine.png', ggAgeLineRecent,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)

```

## Cases, daily cases, 7 day average, last two months

```{r}
ggAgeLineRecentD7 <- ggplot(Age %>% filter(AgeType == 'Age.D7.'),
       aes(x=date(Date), y=Cases, group = AgeGroup,
           colour=AgeGroup, fill=AgeGroup)) +
  geom_line() + geom_point(alpha=0.5) +
#  geom_smooth(span=0.1) +
  scale_y_log10(limits=c(3,1350)) +
#  scale_fill_distiller(palette='OrRd', direction=1,
#                       na.value='white') +
#  scale_colour_brewer(palette='Dark2', direction=1,
#                         na.value='white') +
#  scale_colour_viridis_d(begin='red',end='nlue', direction=1,
 #                        na.value='white') +
  scale_x_date(limits=c(end_date - days(90),
                        end_date + days(7)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Cases') +
  ggtitle('Confirmed COVID19 cases by age',subtitle='All cases, 7 day average') +
  theme_light()

ggAgeLineRecentD7

ggsave('images/COVID19AgeRecentLineD7.png', ggAgeLineRecentD7,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)

```

# Rates per 100,000

```{r}
AgeRate <- Age %>%
  inner_join(Pop %>% select(-Mean.Age.10), by = c("AgeGroup" = "COVID.codes")) %>%
  mutate(AgeGroup = as_factor(AgeGroup)) %>%
  mutate(AgeGroup = fct_reorder(AgeGroup, Mean.Age.10)) %>% # Desired order
  mutate(Cases = pmax(Cases,0)) %>%
  mutate(Rate = 100000*Cases/Population)

glimpse(AgeRate)
glimpse(Age)
glimpse(Pop)
```


```{r}
ggAgeLineRecentRateD7 <- ggplot(AgeRate %>% filter(AgeType == 'Age.D7.'),
       aes(x=date(Date), y=Rate, group = AgeGroup,
           colour=AgeGroup, fill=AgeGroup)) +
  geom_line() + geom_point(alpha=0.5) +
#  geom_smooth(span=0.1) +
  scale_y_log10(limits=c(1,100)) +
#  scale_y_log10(limits=c(1,60)) +
#  scale_fill_distiller(palette='OrRd', direction=1,
#                       na.value='white') +
#  scale_colour_brewer(palette='Dark2', direction=1,
#                         na.value='white') +
#  scale_colour_viridis_d(begin='red',end='nlue', direction=1,
 #                        na.value='white') +
  scale_x_date(limits=c(end_date - days(60),
                        end_date + days(3)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Rate per 100,000') +
  ggtitle('Confirmed COVID19 case rates by age',subtitle='All cases - smoothed 7 day rates') +
  theme_light()

ggAgeLineRecentRateD7

ggsave('images/COVID19AgeRecentLineRateD7.png', ggAgeLineRecentRateD7,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)

```


```{r}
ggAgeLineRecentRate <- ggplot(AgeRate %>% filter(AgeType == 'Age.'),
       aes(x=date(Date), y=Rate, group = AgeGroup,
           colour=AgeGroup, fill=AgeGroup)) +
  geom_line(alpha=0.25) + geom_point(alpha=0.01) +
  geom_smooth(span=0.15, alpha=0.005) +
  scale_y_log10(limits=c(1,100)) +
#  scale_fill_distiller(palette='OrRd', direction=1,
#                       na.value='white') +
#  scale_colour_brewer(palette='Dark2', direction=1,
#                         na.value='white') +
#  scale_colour_viridis_d(begin='red',end='nlue', direction=1,
 #                        na.value='white') +
  scale_x_date(limits=c(end_date - days(60),
                        end_date + days(3)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Rate per 100,000') +
  ggtitle('Confirmed COVID19 case rates by age',subtitle='All cases - daily rates') +
  theme_light()

ggAgeLineRecentRate

ggsave('images/COVID19AgeRecentLineRate.png', ggAgeLineRecentRate,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)

```

```{r}
ggAgeLineRecentRate <- 
ggplot(AgeRate %>% filter(AgeType == 'Age.D7.'),
       aes(x=date(Date), y=Rate, group = AgeGroup,
           colour=AgeGroup, fill=AgeGroup)) +
  geom_line(alpha=0.25) + geom_point(alpha=0.01) +
  geom_vline(xintercept=as_date('2021-08-29'),colour='red') +
  geom_smooth(span=0.15, alpha=0.005) +
  scale_y_continuous(limits=c(1,60)) +
  scale_x_date(limits=c(end_date - days(60),
                        end_date + days(3)),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  xlab('Date') + ylab('Rate per 100,000') +
  ggtitle('Confirmed COVID19 case rates by age',subtitle='All cases - daily rates') +
  theme_light() +
  facet_wrap(~AgeGroup)

ggAgeLineRecentRate

ggsave('images/COVID19AgeRecentLineRate.png', ggAgeLineRecentRate,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)

```
