---
title: "Load data"
author: "Anthony Staines"
date: "13/03/2020"
output: 
  html_document: 
    fig_caption: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

# Purpose
This file is run once a day to download the latest coronavirus data. The Irish data, manually collected each evening from the DoH website (https://www.gov.ie/en/news/7e0924-latest-updates-on-covid-19-coronavirus/) are downloaded separately, and used to correct the JHU data.

```{r setup, include=FALSE}
rm(list=ls())
library(devtools)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## Update
Load the latest accumulated international coronavirus data from GitHub

```{r load}
install_github("RamiKrispin/coronavirus")
```

Check to see if it worked.

```{r test}
library(coronavirus)
data("coronavirus")
glimpse(coronavirus)

```

Do a quick table

```{r some tables}
summary_df <- coronavirus %>% group_by(Country.Region, type) %>%
  summarise(total_cases = sum(cases)) %>%
  arrange(-total_cases)

coronavirus %>% 
  filter(date == max(date)) %>%
  select(country = Country.Region, type, cases) %>%
  group_by(country, type) %>%
  summarise(total_cases = sum(cases)) %>%
  pivot_wider(names_from = type,
              values_from = total_cases) %>%
  arrange(-confirmed)
```

Stop
