---
title: "Coronavirus SIR model"
author: "Anthony Staines"
date: "13/03/2020"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

#Purpose

To prepare SIR models for coronavirus incidence, and short term predictions, in Ireland

```{r setup, include=FALSE}
rm(list=ls())
library(coronavirus) # Coronavirus data
library(propagate) # Errors in non-linear regression models
library(ggrepel) # Nice labels
library(lubridate) # Sane date handling
library(drc)
library(sandwich)
library(lmtest)
library(tidyverse)

data("coronavirus")

knitr::opts_chunk$set(echo = TRUE)
```

## Correct the Irish data
The Irish data contain some errors in the JHU dataset, and are less up-to-date. We donwload the data manually from the website (https://www.gov.ie/en/news/7e0924-latest-updates-on-covid-19-coronavirus/) and add it to an excel file for each day

```{r load data file}
load('data/CC.Rdata')

```

# Get daily cases

```{r}
Ireland <- CC %>%
  filter(Country.Region == 'Ireland') %>%
  filter(type == 'confirmed') %>%
  mutate(Sum = cumsum(cases)) %>%
  filter(Sum >2)
Ireland

Cases <- as_vector(Ireland$cases)
  
#  c(45, 62, 121, 198, 291, 440, 571, 830, 1287, 1975, 2744, 4515, 5974, 7711, 9692, 11791, 14380, 17205, 20440) #China
Day <- 1:(length(Cases))
N <- 4800000 # population of Ireland 2016 census plus a bit
 
old <- par(mfrow = c(1, 2))
plot(Day, Cases, type ="b")
plot(Day, Cases, log = "y")
abline(lm(log10(Cases) ~ Day))
title("Confirmed Cases 2019-nCoV Ireland", outer = TRUE, line = -2)

 SIR <- function(time, state, parameters) {
  par <- as.list(c(state, parameters))
  with(par, {
    dS <- -beta/N * I * S
    dI <- beta/N * I * S - gamma * I
    dR <- gamma * I
    list(c(dS, dI, dR))
    })
}

library(deSolve)
init <- c(S = N-Cases[1], I = Cases[1], R = 0)
RSS <- function(parameters) {
  names(parameters) <- c("beta", "gamma")
  out <- ode(y = init, times = Day, func = SIR, parms = parameters)
  fit <- out[ , 3]
  sum((Cases - fit)^2)
}
 
#Opt <- optim(c(0.5, 0.5), RSS, method = "L-BFGS-B", lower = c(0, 0), upper = c(1, 1)) # optimize with some sensible conditions
Opt <- optim(c(0.6, 0.3), RSS, method = "L-BFGS-B", lower = c(0, 0), upper = c(1, 1)) # optimize with some sensible conditions
Opt$message
## [1] "CONVERGENCE: REL_REDUCTION_OF_F <= FACTR*EPSMCH"
 
Opt_par <- setNames(Opt$par, c("beta", "gamma"))
Opt_par
##      beta     gamma 
## 0.6746089 0.3253912 # China
## 0.5518132 0.3566414 #Ireland
## 1.0000000 0.9023042 # Ireland 28/4
 
t <- 1:200 # time in days
fit <- data.frame(ode(y = init, times = t, func = SIR, parms = Opt_par))
col <- 1:3 # colour
 
matplot(fit$time, fit[ , 2:4], type = "l", xlab = "Day", ylab = "Number of subjects", lwd = 2, lty = 1, col = col)
matplot(fit$time, fit[ , 2:4], type = "l", xlab = "Day", ylab = "Number of subjects", lwd = 2, lty = 1, col = col, log = "y")
## Warning in xy.coords(x, y, xlabel, ylabel, log = log): 1 y value <= 0
## omitted from logarithmic plot
 
points(Day, Cases)
legend("bottomright", c("Susceptibles", "Infecteds", "Recovereds"), lty = 1, lwd = 2, col = col, inset = 0.05)  
  
 
fitw <- fit  %>% pivot_longer(c('S','I','R'),
                              names_to = 'Type', values_to = 'Number')
fitw$Number[fitw$Number == 0] <- 0.5 

ggplot() +
  geom_path(data=fitw,aes(y=Number,x=time, group=Type, colour=Type)) +
  geom_point(data=as_tibble(cbind(Cases,Day)), aes(y=Cases,x=Day)) +
  xlab("Day") + ylab("Number of subjects") +
  scale_y_continuous(trans = "log10")

par(old)
 
R0 <- setNames(Opt_par["beta"] / Opt_par["gamma"], "R0")
R0
##       R0 
## 2.073224 China
## 1.134917 Ireland
 
fit[fit$I == max(fit$I), "I", drop = FALSE] # height of pandemic
##            I
## 50 232001865 China
## 147 35345.59 Ireland
 
max(fit$I) * 0.02 # max deaths with supposed 2% fatality rate
## [1] 4640037
## 706.9119

```
