---
title: "HPSC data"
author: "Anthony Staines"
date: "10/04/2020"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

# Setup

```{r setup, include=FALSE}
library(pdftools)
library(foreach)
library(lubridate)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

This is a list of all the pdfs in the HPSC directory, and the date each report was issued.

```{r file list}
Filenames <- list.files('HPSC',full.names = TRUE) %>%
  tibble() 
names(Filenames) <- c('File')

Files <- Filenames %>%
  mutate(Date = str_extract(File, pattern = "(?<=report for NPHET )(.{8})")) %>%
  # selects the next 8 characters after the text
  mutate(Date = parse_date_time(Date, c("dmy", "ymd"))) %>% # Order matters
  arrange(Date)

rm(Filenames)
```

This loops over the list of file names, and reads all the files into a common data structure.

```{r Read Many}
HPSC_total <- foreach (I = seq(1,length(Files$File))) %do% {
  print(Files$File[I])
  
  HPSC_text <- pdf_text(Files$File[I]) %>%
  readr::read_lines() %>%
  tibble()
HPSC_text <- HPSC_text[10:24,]
head(HPSC_text)

names(HPSC_text) <- c('Text') # Otherwise the name is '.', which is not a good choice!

HPSC <- HPSC_text %>% ## Empirically tidy up the content.
    mutate(Text = str_replace_all(Text,'     March',' March')) %>% # Replace excess spaces on 24/3/20
  mutate(Text = str_replace_all(Text,'  ','|')) %>% # Replace two spaces with one |
  mutate(Text = str_replace_all(Text,'\\| ','|')) %>% # Remove spaces after a |
  mutate(Text = str_replace_all(Text,' \\|','|')) %>% # Remove spaces before a |
  mutate(Text = str_replace_all(Text,'^\\|+','')) %>% # Remove all initial | characters
  mutate(Text = str_replace_all(Text,'\\|+','|')) %>% # Replace multiple | with one |
  mutate(Text = str_replace_all(Text,'\\*','')) %>% # Remove an * (for a footnote)
  mutate(Text = str_replace_all(Text,',','')) %>% # Remove a comma
  mutate(Text = str_replace_all(Text,'\\/',' or ')) %>% # Replace a / with an or
  mutate(Text = str_replace_all(Text,'\\%','')) %>% # Replace % with Pct.
  #mutate(Text = str_replace_all(Text,'(\\d+)(\\S+)(\\d+)','\\1,|,\\3')) %>% # cope with single spaces
  mutate(Text = trimws(Text)) # Remove extra intial whitespace in most recent files
  
#write_csv(HPSC,'data/temp.csv') # Can't figure how to read_delim from a tibble?
#'data/temp.csv'
  
HPSC <- read_delim(HPSC$Text, delim='|',
                   skip=1, na = c('-'),
                   col_names = c('Characteristic','Number','Pct')) %>%
    mutate(Date = Files$Date[I]) %>%
  mutate(Number = as.character(Number)) %>%
  mutate(Pct = as.character(Pct))
  
print(HPSC)
}

```

# Merge into one file

```{r}
HPSC <- bind_rows(HPSC_total) %>%  # one row per row in tables
  filter(!(is.na(Number) & is.na(Pct))) %>% # No numeric data in row
  filter(Characteristic != "Page") %>%
  filter(Characteristic != "Characteristic") %>% # Irrelevant rows
  mutate(Date = as_date(Date))

table(HPSC$Characteristic)

glimpse(HPSC)

# Add the date to which the report refers.
HPSC <- HPSC %>%
  mutate(ApplicableDate = 
         Date -2) %>% # Date of events - two days before report date
  mutate(Characteristic = 
         ifelse(str_detect(Characteristic,"Number of new cases *"),
                           "Number of new cases",
                           Characteristic)) %>%
  mutate(Characteristic = 
         ifelse(str_detect(Characteristic,
                           "Number of cases in Healthcare workers"),
                           "Number of cases in HCW",
                           Characteristic)) %>%
  mutate(Characteristic = trimws(Characteristic)) %>%
  mutate(RecordDate = ApplicableDate)

glimpse(HPSC)

table(HPSC$Characteristic)

HH <- HPSC %>%
  select(-Pct, -ApplicableDate, -Date) %>%
    # Some of the numbers have a number, a space and a second number,
    # because only 1 space seperated them in the file when it was read
    mutate(Number = ifelse(
    str_detect(Number,'(\\d+)(\\s+)(\\d+)'), 
    str_extract(Number,'\\d+'), # If so, pull out the first number only, second is a stray percentage
    Number)) %>%                # If not, let it pass
  pivot_wider(names_from = Characteristic, values_from=Number)

names(HH)
# [1] "RecordDate"                                  "Total number of confirmed cases"            
# [3] "Number of new cases"                         "Total number hospitalised"                  
# [5] "Total number admitted to ICU"                "Total number of deaths"                     
# [7] "Case Fatality Ratio (CFR )"                  "Total number of outbreaks or clusters"      
# [9] "Total number cases associated with clusters" "Total number of imported cases"             
#[11] "Number of cases in HCW"                      "Median age (years)"                         
#[13] "Age range (years)"                          

names(HH) <- c("Date", "Confirmed", "New", "Hospitalised", "ICU", "Deaths", "CFR", "OutbreakNos", "OutbreakCases", "ImportedCases", "HCWCases", "AgeMedian", "AgeRange")

HH <- HH %>%
  mutate_if(is.character, as.numeric) # Warning message: NAs introduced by coercion

glimpse(HH)  
```

Everything, except the New Cases, the CFR, and the MedianAge, is a cumulative total, so we need the differences from Day 1.

```{r Differences}
HH$Confirmed
diff(HH$Confirmed)

HH.diff <- HH %>%
  modify_if(is.numeric,~(. - lag(.))) %>%
  mutate(New = HH$New, CFR = HH$CFR,AgeMedian = HH$AgeMedian)
  
glimpse(HH.diff)

```

```{r}
g <- ggplot(data=HH.diff,aes(x=Date, y=New)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('New cases') + xlab('Date') +
  ggtitle('HPSC data on new cases') +
  theme_grey(base_size = 22)
g
ggsave('images/HPSC_Hospitals.png',g,
       units='cm', dpi=600, width=21, height=15)

g <- ggplot(data=HH.diff,aes(x=Date, y=Hospitalised)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('Hospital admissions') + xlab('Date') +
  ggtitle('HPSC data on hospitalisations') +
  theme_grey(base_size = 22)
g
ggsave('images/HPSC_Hospitals.png',g,
       units='cm', dpi=600, width=21, height=15)


g <- ggplot(data=HH.diff,aes(x=Date, y=Deaths)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ggtitle('HPSC data on deaths') +
  theme_grey(base_size = 22) 
g
ggsave('images/HPSC_Deaths.png',g,
       units='cm', dpi=600, width=21, height=15)


g <- ggplot(data=HH.diff,aes(x=Date, y=ICU)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('ICU admissions') + xlab('Date') +
  ggtitle('HPSC data on ICU admissions') +
  theme_grey(base_size = 22) 
g
ggsave('images/HPSC_ICU.png',g,
       units='cm', dpi=600, width=21, height=15)

g <- ggplot(data=HH.diff,aes(x=Date, y=OutbreakCases)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('Outbreak cases') + xlab('Date') +
  ggtitle('HPSC data on cases in outbreaks') +
  theme_grey(base_size = 22) 
g
ggsave('images/HPSC_OutbreakCases.png',g,
       units='cm', dpi=600, width=21, height=15)

g <- ggplot(data=HH.diff,aes(x=Date, y=OutbreakNos)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('Outbreak numbers') + xlab('Date') +
  ggtitle('HPSC data on number of outbreaks') +
  theme_grey(base_size = 22) 
g
ggsave('images/HPSC_OutbreakNos.png',g,
       units='cm', dpi=600, width=21, height=15)
g1 <- g

g <- ggplot(data=HH.diff,aes(x=Date, y=OutbreakCases/OutbreakNos)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('Outbreak size') + xlab('Date') +
  ggtitle('HPSC data on cases per outbreak') +
  theme_grey(base_size = 22)  + coord_cartesian(ylim = (c(0,30)))
g
ggsave('images/HPSC_OutbreakSize.png',g,
       units='cm', dpi=600, width=21, height=15)

g2 <- g
g <- ggpubr::ggarrange(g1,g2,ncol=1)
g
ggsave('images/HPSC_Care_Cases_Size.png',g,
       units='cm', dpi=600, width=21, height=15)

g <- ggplot(data=HH.diff,aes(x=Date, y=HCWCases)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('Cases in HCW') + xlab('Date') +
  ggtitle('HPSC data on cases in HCWs') +
  theme_grey(base_size = 22) 
g
ggsave('images/HPSC_HCW.png',g,
       units='cm', dpi=600, width=21, height=15)

HH.diff <- HH.diff %>%
  mutate(Community = New - OutbreakCases - HCWCases)

g <- ggplot(data=HH.diff,aes(x=Date, y=Community)) +
  geom_point(colour='blue') +
  geom_smooth(color='grey',fill='pink',alpha=0.2) +
  scale_x_date(limits=c(as_date('2020-03-21'),as_date('2020-05-14'))) +
  ylab('Cases in Community?') + xlab('Date') +
  ggtitle('HPSC data on cases in Community',
          subtitle='Formally meaningless') +
  theme_grey(base_size = 22) 
g
ggsave('images/HPSC_CommunityCases.png',g,
       units='cm', dpi=600, width=21, height=15)

rm(g,g1,g2)
```


## Write out data

```{r Write out data}

HH %>% write_csv('data/HPSC reported data.csv')
HH.diff %>% write_csv('data/HPSC calcualted daily data.csv')

rm(HH,HH.diff,HPSC,HPSC_t,HPSC_text,HPSC_total,Files,I)

```

