---
title: "Ireland in Context"
author: "Anthony Staines"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: 
    fig_caption: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

#Purpose

To show Irish data in context.

```{r setup, include=FALSE}
rm(list=ls())
library(lubridate) # Sane date handling
library(tidyverse)

set.seed(6564)


knitr::opts_chunk$set(echo = FALSE, cache=TRUE)
```

# Load the prepared data with the Irish data manually corrected

```{r load data file}
JHU_C_iso <- readRDS('data/JHU_C_iso.rds')

  start_date = min(JHU_C_iso$date)
  end_date = max(JHU_C_iso$date)
Span = as.numeric(end_date - start_date)

```

```{r Fix data file to suit}
str(JHU_C_iso)
table(JHU_C_iso$type, useNA = 'ifany')
table(JHU_C_iso$country, useNA = 'ifany')
table(JHU_C_iso$province, useNA = 'ifany')

JHU_C_iso %>% filter(is.na(province))
```

# Define areas for comparison

```{r define areas for comparisons}
EU <- c('Austria', 'Italy', 'Belgium', 'Latvia', 'Bulgaria', 'Lithuania', 'Croatia', 'Luxembourg', 'Cyprus', 'Malta', 'Czechia', 'Netherlands', 'Denmark', 'Poland', 'Estonia', 'Portugal', 'Finland', 'Romania', 'France', 'Slovakia', 'Germany', 'Slovenia', 'Greece', 'Spain', 'Hungary', 'Sweden', 'Ireland')

Anglo <- c('United Kingdom','Australia','New Zealand', 'US', 'Ireland')

Context <- c('Austria', 'Italy', 'Belgium', 'Czechia', 'Netherlands', 'Denmark', 'Portugal', 'Finland', 'France', 'Germany', 'Greece', 'Spain', 'Sweden', 'Ireland', 'United Kingdom','Australia','New Zealand')

Islands <- c()
```

```{r create datasets of cases and deaths and Ireland}
JHU_Confirmed <- JHU_C_iso %>%
  filter(type == 'confirmed') %>%
  mutate(cases = casesAdj) # Set negative cases to 0

JHU_Dead      <- JHU_C_iso %>%
  filter(type == 'death') %>%
  mutate(deaths = casesAdj) # Set negative cases to 0

Ireland_Confirmed <- JHU_Confirmed %>% filter(country == 'Ireland')
Ireland_Dead <- JHU_Dead %>% filter(country == 'Ireland')
```

## Locate labels
Reasonable set of defaults for label positions.

```{r}

#Set of dates to play with
Latest_date <- JHU_C_iso %>%
  group_by(country, type) %>% # Type within country
  mutate(weight = 1 - 2*as.numeric(end_date - date)/Span) %>% #weight more recent ranks more heavily
  mutate(wtrate = rate * weight) %>%
  mutate(rank = round(rank(-wtrate))) %>%
  filter(rank == 50) %>%
  ungroup() %>%
  mutate(WEEKS = round(runif(n(),min=-1,max=+15),0)) %>% # Spread dates over 12 weeks
  mutate(date = as_date(date - weeks(WEEKS))) %>%
  select(-WEEKS) %>%
  mutate(date = replace(date, country == 'Ireland', as_date('2021-01-06'))) %>%
  mutate(rate = replace(rate, country == 'Ireland', 1050))


```

# Plots of case numbers

```{r}

ggContext <- ggplot(JHU_Confirmed %>%
         filter(country %in% Context, province == ''),
       aes(x=date(date), y=cases,
           group=country, colour=country, label=country))+
  geom_smooth(data = Ireland_Confirmed,
              alpha = 0.6, span = 0.1,
              se = FALSE, size = .8) +
  geom_smooth(aes(group = country),
              alpha = 0.05, span = 0.1,
              se = FALSE, size = 0.2) +
  geom_jitter(alpha = 0.1, size = 0.2) +
  ggrepel::geom_text_repel(data = Latest_date %>%
                             filter(country %in% Context,
                                    type == 'confirmed'),
                           max.overlaps = 20,
                        aes(x= date, y = rate*10, label = country)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10() +
  xlab('Date') + ylab('Cases (log scale)') +
  ggtitle('Confirmed COVID19 Cases over time (smoothed)',
          subtitle = 'Selected European countries') +
  guides(fill=FALSE) +
  guides(colour=FALSE) +
  geom_label(aes(x = as_date(min(date) + Span*5/100),
                 y = max(cases)- max(cases*5/100)),
             colour = 'blue', fill = 'lightblue',
             label='@isagcovid19') +
  theme_light()

ggContext


ggsave('images/Ireland_cases_in_context.png', ggContext,
       units = 'cm', dpi = 600, width = 21, height = 15)
```

# Plots of case rates per million

```{r}
#Locate labels
ggContextRates <- ggplot(JHU_Confirmed %>%
         filter(country %in% Context, province == ''),
       aes(x=date(date), y=rate,
           group=country, colour=country, label=country))+
  geom_smooth(data = Ireland_Confirmed,
              alpha = 0.6, span = 0.1,
              se = FALSE, size = .8) +
  geom_smooth(aes(group = country),
              alpha = 0.05, span = 0.1,
              se = FALSE, size = 0.2) +
#  geom_jitter(alpha = 0.1, size = 0.2) +
  ggrepel::geom_text_repel(data = Latest_date %>%
                             filter(country %in% Context,
                                    type == 'confirmed'),
                           aes(x= date, y = rate, label = country)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Rates (Cases per million per day)') +
  ggtitle('Confirmed COVID19 Rates over time (smoothed)',
          subtitle = 'Selected European countries') +
  guides(fill=FALSE) +
  guides(colour=FALSE) +
  geom_label(aes(x = as_date(min(date) + Span*5/100),
                 y = max(rate)/2),
             colour = 'blue', fill = 'lightblue',
             label='@isagcovid19') +
  theme_light()

ggContextRates

ggsave('images/Ireland_case_rates_in_context.png', ggContextRates,
       units = 'cm', dpi = 600, width = 21, height = 15)

ggContextRatesShort <- ggContextRates +
  scale_x_date(limits = c(end_date - 60, end_date+7)) #+
#  geom_label(aes(x = start_date + Span*5/100,
#                 y = max(rate)/2),
#             colour = 'blue', fill = 'lightblue',
#             label='@isagcovid19') 

ggContextRatesShort

ggsave('images/Ireland_case_rates_short_in_context.png', ggContextRatesShort,
       units = 'cm', dpi = 600, width = 21, height = 15)

```

# Plots of death numbers

```{r Deaths}

ggDeathsContext <- ggplot(JHU_Dead %>%
                            filter(country %in% Context, province == ''),
       aes(x=date(date), y=cases,
           group=country, colour=country, label=country))+
  geom_smooth(aes(group = country),
              alpha = 0.05, span = 0.3,
              se = FALSE, size = 0.2) +
  geom_smooth(data = Ireland_Dead,
              alpha = 0.6, span = 0.3,
              se = FALSE, size = .8) +
  ggrepel::geom_text_repel(data = Latest_date %>%
                             filter(country %in% Context,
                                    type == 'death'),
                           aes(x= date, y = cases, label = country)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10(limits=c(1,1000)) +
  xlab('Date') + ylab('Deaths (log scale)') +
  ggtitle('Confirmed COVID19 deaths over time',
          subtitle = 'Selected European countries') +
  guides(fill=FALSE) +
  guides(colour=FALSE) +
  geom_label(aes(x = as_date(min(date) + Span*5/100),
                 y = max(rate)/2),
             colour = 'blue', fill = 'lightblue',
             label='@isagcovid19') +
  theme_light()

ggDeathsContext

ggsave('images/Ireland_deaths_in_context.png', ggDeathsContext,
       units = 'cm', dpi = 600, width = 21, height = 15)
```


# Plots of death rates

```{r Deaths}

ggDeathRateContext <- ggplot(JHU_Dead %>%
                            filter(country %in% Context, province == ''),
       aes(x=date(date), y=cases,
           group=country, colour=country, label=country))+
  geom_smooth(aes(group = country),
              alpha = 0.5, span = 0.4,
              se = FALSE, size = 0.2) +
  geom_smooth(data = Ireland_Dead,
              alpha = 0.6, span = 0.4,
              se = FALSE, size = .8) +
  ggrepel::geom_text_repel(data = Latest_date %>%
                             filter(country %in% Context,
                                    type == 'death'),
                           aes(x= date, y = cases, label = country)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10(limits=c(1,1000)) +
  xlab('Date') + ylab('Death rates per 100k (log scale)') +
  ggtitle('Confirmed COVID19 deaths, rate over time',
          subtitle = 'Selected European countries') +
  guides(fill=FALSE) +
  guides(colour=FALSE) +
  geom_label(aes(x = as_date(min(date) + Span*5/100),
                 y = max(rate)/2),
             colour = 'blue', fill = 'lightblue',
             label='@isagcovid19') +
  theme_light()

ggDeathRateContext

ggsave('images/Ireland_deaths_rate_in_context.png', ggDeathRateContext,
       units = 'cm', dpi = 600, width = 21, height = 15)
```



