---
title: "Time trends"
author: "Anthony Staines"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: 
    fig_caption: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

#Purpose
To prepare graphs of coronavirus incidence over time.

```{r setup, include=FALSE}
rm(list=ls())

library(RcppRoll)
library(lubridate)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

# Load the data
Latest HSE/HPSC data

```{r}
Irish_Current <- readRDS('data/Irish_Current.rds')
  start_date = min(Irish_Current$Date)
  end_date = max(Irish_Current$Date) + days(14)

Lab_RecordsCSV <-  readRDS('data/Lab_RecordsCSV.rds')
```

# Cases

```{r}
ggCases <- ggplot(Irish_Current,aes(x=date(Date),y=ConfirmedCovidCases)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10() +
  xlab('Date') + ylab('Cases (log scale)') +
  ggtitle('Confirmed COVID19 cases over time') +
  theme_light()

ggCases

ggsave('images/COVID19Caseslogscale.png', ggCases,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

# Deaths

```{r}
ggDeaths <- ggplot(Irish_Current,aes(x=date(Date),y=ConfirmedCovidDeaths)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10() +
  xlab('Date') + ylab('Cases (log scale)') +
  ggtitle('Confirmed COVID19 deaths over time') +
  theme_light()

ggDeaths

ggsave('images/COVID19Deathslogscale.png', ggDeaths,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

# Load the profile data

```{r}
Irish_Profile <- readRDS('data/Irish_Profile.rds') %>%
  filter(!is.na(CovidCasesConfirmed))

start_date = min(Irish_Profile$Date)
end_date = max(Irish_Profile$Date) + days(14)

```

# Admissions

```{r}
ggAdmissions <- ggplot(Irish_Profile,aes(x=date(Date),y=Admissions)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
  scale_y_log10() +
  xlab('Date') + ylab('Cases (log scale)') +
  ggtitle('Hospitalised COVID19 Cases over time') +
  theme_light()

ggAdmissions

ggsave('images/COVID19Admissionslogscale.png', ggAdmissions,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

# ICU Admissions

```{r}
ggICU <- ggplot(Irish_Profile,aes(x=date(Date),y=ICU)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Cases') +
  ggtitle('Hospitalised COVID19 Cases in ICU over time') +
  theme_light()

ggICU

ggsave('images/COVID19ICUlogscale.png', ggICU,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

# Laboratory data

```{r}
Lab_Records <- readRDS(file='data/Lab_Records.rds')

```


```{r}
ggTests <- ggplot(Lab_Records,aes(x=date(Date),y=TestsDone)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Tests') +
  ggtitle('Laboratory tests done') +
  theme_light()

ggTests

ggsave('images/LabTestsDone.png', ggTests,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```


```{r}
ggTestsPos <- ggplot(Lab_Records,aes(x=date(Date),y=TestsPos)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Tests') +
  ggtitle('Positive tests number') +
  theme_light()

ggTestsPos

ggsave('images/LabTestsPos.png', ggTestsPos,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

```{r}
ggTestsPosPct <- ggplot(Lab_Records,aes(x=date(Date),y=PosRate)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Percentage tests positive') +
  ggtitle('Positive tests %') +
  theme_light()

ggTestsPosPct

ggsave('images/LabTestsPosPct.png', ggTestsPosPct,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```


## Positive tests and recorded cases

```{r}
Cases <- Irish_Current %>% select(Date,ConfirmedCovidCases)
Tests <- Lab_Records %>% select(Date,TestsDone,TestsPos)
Linked <- Cases %>% inner_join(Tests) %>%
  mutate(Diff = TestsPos - ConfirmedCovidCases) %>%
  mutate(DiffCasePct = 100*Diff/ConfirmedCovidCases) %>%
  mutate(DiffTestsPct = 100*Diff/TestsPos)

ggplot(Linked,aes(x=date(Date),y=Diff)) +geom_path()
ggplot(Linked,aes(x=date(Date), y=DiffCasePct)) +geom_path() +geom_smooth()
ggplot(Linked,aes(x=date(Date), y=DiffTestsPct)) +geom_path() +geom_smooth()


saveRDS(Linked,file='data/Linked.rds')
```

```{r}

ggTestsCases <- ggplot(Linked,aes(x=date(Date),y=TestsPos)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  geom_path(aes(y=ConfirmedCovidCases),alpha=0.1,colour='lightgreen') +
  geom_point(aes(y=ConfirmedCovidCases),alpha=0.3,colour='lightgreen') +
  geom_smooth(aes(y=ConfirmedCovidCases),alpha=0.1,span=0.2,se=FALSE,colour='lightgreen') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Tests positive') +
  ggtitle('Positive tests (N)') +
  theme_light()

ggTestsCases

ggsave('images/TestsCases.png', ggTestsCases,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

```{r}

Linked <- Linked %>%
  mutate(TestsPosPct = 100*TestsPos/TestsDone)

ggTestsCasesPct <- ggplot(Linked,aes(x=date(Date),y=TestsPosPct)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Percentage tests positive') +
  ggtitle('Positive tests (%)') +
  theme_light()

ggTestsCasesPct

ggsave('images/TestsCasesPct.png', ggTestsCasesPct,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```

```{r}

ggDiff <- ggplot(Linked,aes(x=date(Date),y=Diff)) +
  geom_path(alpha=0.1) +
  geom_smooth(alpha=0.1,span=0.2,se=FALSE,colour='pink') +
  geom_point(alpha=0.3,colour='blue') +
  scale_x_date(limits=c(start_date, end_date),
               date_breaks = "1 month",
               date_labels = "%b",
               date_minor_breaks = "1 week") +
#  scale_y_log10() +
  xlab('Date') + ylab('Difference') +
  ggtitle('Difference between Positive tests and Confirmed cases over time') +
  theme_light()

ggDiff

ggsave('images/Diff.png', ggDiff,
       device = 'png', width = 20, height = 10, units = 'cm', dpi = 600)
```