---
title: "COVID Bounce"
author: "Anthony Staines"
date: "Updated `r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: yes
  html_document:
    highlight: haddock
    keep_md: yes
    theme: spacelab
    toc: yes
  word_document: default
editor_options: 
  chunk_output_type: console
---
# Setup

```{r setup, message=FALSE,warning=FALSE,echo=FALSE,results='hide'}
rm(list=ls())
library(knitr)
library(lubridate)
library(tidyverse)

my.ggsave <- function(plot=last_plot(),filename = default_name(plot),
                      path='images/',height= 200,width= 285,
                      units="mm",dpi= 600, ...) {
                      ggsave(filename=paste(path,filename,sep=''),
        height=height, width=width, units=units,
        dpi=dpi, ...)
}
opts_chunk$set(dev="png", 
               dev.args=list(type="cairo"),
               dpi=300)

opts_chunk$set(error=TRUE,warning=FALSE,message=FALSE,echo=TRUE,cache=TRUE,digits=2)
```


```{r load data file}
load('data/CC.Rdata')
load('data/HH.Rdata')

```

```{r}
HPSC_data <- HPSC_data %>%
mutate(Cases = CovidCasesConfirmed -
           lag(CovidCasesConfirmed, default = 0)) %>%
  mutate(Cases = ifelse(Cases > 0,Cases,0)) %>%
  filter(date > '2020-03-16') # First cases in dataset
ggplot(data=HPSC_data,aes(x=date,y=Cases)) +geom_point()
ggplot(data=HPSC_data,aes(x=date,y=log(Cases))) +geom_point()
```

```{r}
startdate <- min(HPSC_data$date)
lastdata <- max(HPSC_data$date)
enddate <- ymd('2021-09-01') # September 2021
datelist <- seq(startdate, enddate, by='days')
```

# Synthetic data
```{r}
Synth <- as_tibble(datelist)
names(Synth) <- 'Date'

Synth <- Synth %>%
  full_join((HPSC_data %>% select(date,Cases)), by = c('Date' = 'date')) %>%
  mutate(Change = 1)

Breakpoints <- c(lastdata,lastdata+60,lastdata+120, lastdata+180,lastdata+240, lastdata+300)
Breakpoints
Lamda1 <- median(HPSC_data$Cases[149:159])


```

```{r}
Lamda <- 



```

